TEA-16-Implement-Docker-for-Go
CommuniTEAM/CommuniTEA pull request #9
Opened 2023-11-09 02:03 UTC by BMLx23

Changed the count in App.tsk from count +=1 to count +=2. 
Testing the pull request from Jira.

2023-11-17 07:48 UTC, BMLx23 commented
### In this PR, I'm adding/changing the following:
- Added a "backend" directory to contain all the backend work
- containerized golang using docker
- installed cosmtrek-air to re-compile golang changes on refresh instead of rerunning docker to see changes.

**To test my code:**
- You need to rebuild docker: I used these 3 docker commands.
  - docker system prune
  - docker compose build
  - docker compose up
- Go to **http://localhost:8000/** to see if the docker server is running
- Make changes to the main.go file in the ./backend/cmd directory and refresh the page. You should be able to see the new changes without needing to rerun docker.
  - I suggest you make changes to the string in the function:
```
  func (h *homeHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 w.Write([]byte("This is my home page"))
}
```
  - You can change "This is my home page" to a different phrase and see the changes when you refresh the page.

2023-11-17 22:44 UTC, angelajfisher requested changes
It works great and runs beautifully, thanks so much Brian!! Just some small tweaks before it's ready to be merged in.

Aside from the small changes I suggested in my code review, I also ran into this issue when attempting to docker compose:
![docker compose error](https://github.com/CommuniTEAM/CommuniTEA/assets/31549337/195ece8f-68bb-4da1-8679-eb5b2b9295cc)
I was able to fix this by renaming the `dockerfile.dev` to `Dockerfile.dev` as it is referred to in the `docker-compose.yaml`. Everything else worked smoothly in my testing!

2023-11-17 22:44 UTC, angelajfisher commented on .env
It might be safest to follow best practices and keep the `.env` in the `.gitignore`. We can add these values to the `.env.sample` so that they are still tracked, then devs can copy them over to their local `.env` files. This way any potentially sensitive data added to the `.env` later on won't be at risk of exposure.

2023-11-17 22:44 UTC, angelajfisher commented on .gitignore
> +# .env
I see that you already intend to `.gitignore` the `.env` at some point in the future; my suggestion would be to have it ignored from the start so that we don't have to worry about whether it's tracked or not later down the line.

2023-11-17 22:44 UTC, angelajfisher commented on backend/.air.toml
> +exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
I believe these are relative paths, so because `.air.toml` file is within `/backend`, I think `"frontend/node_modules"` resolves to `/backend/frontend/node_modules`

It doesn't hurt anything to include it here, but I don't think it is excluding the intended directory. Anything outside of `/backend` is ignored by default I think; I haven't been able to trigger a recompile by changing anything on the frontend in my tests.

2023-11-17 23:48 UTC, BMLx23 commented on .gitignore
> +# .env
It wasn't ignored just yet because I thought we needed everyone to pull the new changes in main once it is merged. Or else the .env won't show up in the pull. And then afterward we would add it to .gitignore. Will people still be able to pull the .env if we ignore it early?

2023-11-17 23:57 UTC, BMLx23 commented on .gitignore
> +# .env
nvm I saw the previous message of using the .env.sample. Sounds good I will do the ignore early.

2023-11-18 00:20 UTC, BMLx23 commented on backend/.air.toml
> +exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
We also haven't changed the app directory to frontend yet. So we don't have a frontend/node_modules. I can just remove it since it doesn't seem to be doing anything.

2023-11-20 02:01 UTC, deguzmancory approved these changes

2023-11-20 20:12 UTC, angelajfisher approved these changes
Looks great!! Thanks so much!

2023-11-20 20:14 UTC, deguzmancory approved these changes

2023-11-20 20:15 UTC, merged